version: "3.8"
services:
  app:
    build: ./docker/php
    volumes:
      - ./backend:/work
  web:
    image: nginx:1.18-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  redis:
    image: "redis:latest"
    restart: always
    environment:
      - TERM=xterm
    ports:
      - "6379:6379"

volumes:
  db-store: